CREATE TABLE games (
    game_id varchar(255) PRIMARY KEY,
    away_team varchar(255),
    home_team varchar(255),
    start_time DATE,
    sport_key varchar(255),
    sport_title varchar(255)
);


CREATE TABLE odds (
    odds_id varchar(255) PRIMARY KEY,
    game_id varchar(255),
    away_team varchar(255),
    home_team varchar(255),
    start_time DATE,
    sport_key varchar(255),
    sport_title varchar(255),
    sportsbook varchar(255),
    last_update DATE,
    H2H_home_price FLOAT(5,2),
    H2H_away_price FLOAT(5,2),
    home_spread FLOAT(3,1),
    away_spread FLOAT(3,1),
    spread_home_price FLOAT(5,2),
    away_home_price FLOAT(5,2),
    over FLOAT(4,1),
    under FLOAT(4,1),
    over_price FLOAT(5,2),
    under_price FLOAT(5,2)
);


CREATE TABLE sports_mlb (
    game_id varchar(255) PRIMARY KEY,
    away_team varchar(255),
    home_team varchar(255),
    start_time DATE,
    sport_key varchar(255),
    sport_title varchar(255),
    1_SportsbookH2H_home_price varchar(255),
    1_H2H_home_price FLOAT(5,2) ,
    2_SportsbookH2H_home_price varchar(255),
    2_H2H_home_price FLOAT(5,2),
    3_SportsbookH2H_home_price varchar(255),
    3_H2H_home_price FLOAT(5,2),
    1_SportsbookH2H_away_price varchar(255),
    1_H2H_away_price FLOAT(5,2),
    2_SportsbookH2H_away_price varchar(255),
    2_H2H_away_price FLOAT(5,2),
    3_SportsbookH2H_away_price varchar(255),
    3_H2H_away_price FLOAT(5,2),
    1_Sportsbook_spread_home_price varchar(255),
    1_spread_home_price FLOAT(5,2),
    1_home_spread FLOAT(4,1),
    2_Sportsbook_spread_home_price varchar(255),
    2_spread_home_price FLOAT(5,2),
    2_home_spread FLOAT(4,1),
    3_Sportsbook_spread_home_price varchar(255),
    3_spread_home_price FLOAT(5,2),
    3_home_spread FLOAT(4,1),
    1_Sportsbook_spread_away_price varchar(255),
    1_spread_away_price FLOAT(5,2),
    1_away_spread FLOAT(4,1),
    2_Sportsbook_spread_away_price varchar(255),
    2_spread_away_price FLOAT(5,2),
    2_away_spread FLOAT(4,1),
    3_Sportsbook_spread_away_price varchar(255),
    3_spread_away_price FLOAT(5,2),
    3_away_spread FLOAT(4,1),
    1_Sportsbook_over_price varchar(255),
    1_over_price FLOAT(5,2),
    1_over FLOAT(4,1),
    2_Sportsbook_over_price varchar(255),
    2_over_price FLOAT(5,2),
    2_over FLOAT(4,1),
    3_Sportsbook_over_price varchar(255),
    3_over_price FLOAT(5,2),
    3_over FLOAT(4,1),
    1_Sportsbook_under_price varchar(255),
    1_under_price FLOAT(5,2),
    1_under FLOAT(4,1),
    2_Sportsbook_under_price varchar(255),
    2_under_price FLOAT(5,2),
    2_under FLOAT(4,1),
    3_Sportsbook_under_price varchar(255),
    3_under_price FLOAT(5,2),
    3_under FLOAT(4,1),
    1_H2H_home_price_ST varchar(255),
    2_H2H_home_price_ST varchar(255),
    3_H2H_home_price_ST varchar(255),
    1_H2H_away_price_ST varchar(255),
    2_H2H_away_price_ST varchar(255),
    3_H2H_away_price_ST varchar(255),
    1_spread_home_price_ST varchar(255),
    2_spread_home_price_ST varchar(255),
    3_spread_home_price_ST varchar(255),
    1_spread_away_price_ST varchar(255),
    2_spread_away_price_ST varchar(255),
    3_spread_away_price_ST varchar(255),
    1_over_price_ST varchar(255),
    2_over_price_ST varchar(255),
    3_over_price_ST varchar(255),
    1_under_price_ST varchar(255),
    2_under_price_ST varchar(255),
    3_under_price_ST varchar(255)
);


CREATE TABLE sports_nba (
    game_id varchar(255) PRIMARY KEY,
    away_team varchar(255),
    home_team varchar(255),
    start_time DATE,
    sport_key varchar(255),
    sport_title varchar(255),
    1_SportsbookH2H_home_price varchar(255),
    1_H2H_home_price FLOAT(5,2) ,
    2_SportsbookH2H_home_price varchar(255),
    2_H2H_home_price FLOAT(5,2),
    3_SportsbookH2H_home_price varchar(255),
    3_H2H_home_price FLOAT(5,2),
    1_SportsbookH2H_away_price varchar(255),
    1_H2H_away_price FLOAT(5,2),
    2_SportsbookH2H_away_price varchar(255),
    2_H2H_away_price FLOAT(5,2),
    3_SportsbookH2H_away_price varchar(255),
    3_H2H_away_price FLOAT(5,2),
    1_Sportsbook_spread_home_price varchar(255),
    1_spread_home_price FLOAT(5,2),
    1_home_spread FLOAT(4,1),
    2_Sportsbook_spread_home_price varchar(255),
    2_spread_home_price FLOAT(5,2),
    2_home_spread FLOAT(4,1),
    3_Sportsbook_spread_home_price varchar(255),
    3_spread_home_price FLOAT(5,2),
    3_home_spread FLOAT(4,1),
    1_Sportsbook_spread_away_price varchar(255),
    1_spread_away_price FLOAT(5,2),
    1_away_spread FLOAT(4,1),
    2_Sportsbook_spread_away_price varchar(255),
    2_spread_away_price FLOAT(5,2),
    2_away_spread FLOAT(4,1),
    3_Sportsbook_spread_away_price varchar(255),
    3_spread_away_price FLOAT(5,2),
    3_away_spread FLOAT(4,1),
    1_Sportsbook_over_price varchar(255),
    1_over_price FLOAT(5,2),
    1_over FLOAT(4,1),
    2_Sportsbook_over_price varchar(255),
    2_over_price FLOAT(5,2),
    2_over FLOAT(4,1),
    3_Sportsbook_over_price varchar(255),
    3_over_price FLOAT(5,2),
    3_over FLOAT(4,1),
    1_Sportsbook_under_price varchar(255),
    1_under_price FLOAT(5,2),
    1_under FLOAT(4,1),
    2_Sportsbook_under_price varchar(255),
    2_under_price FLOAT(5,2),
    2_under FLOAT(4,1),
    3_Sportsbook_under_price varchar(255),
    3_under_price FLOAT(5,2),
    3_under FLOAT(4,1),
    1_H2H_home_price_ST varchar(255),
    2_H2H_home_price_ST varchar(255),
    3_H2H_home_price_ST varchar(255),
    1_H2H_away_price_ST varchar(255),
    2_H2H_away_price_ST varchar(255),
    3_H2H_away_price_ST varchar(255),
    1_spread_home_price_ST varchar(255),
    2_spread_home_price_ST varchar(255),
    3_spread_home_price_ST varchar(255),
    1_spread_away_price_ST varchar(255),
    2_spread_away_price_ST varchar(255),
    3_spread_away_price_ST varchar(255),
    1_over_price_ST varchar(255),
    2_over_price_ST varchar(255),
    3_over_price_ST varchar(255),
    1_under_price_ST varchar(255),
    2_under_price_ST varchar(255),
    3_under_price_ST varchar(255)
);


CREATE TABLE sports_nhl (
    game_id varchar(255) PRIMARY KEY,
    away_team varchar(255),
    home_team varchar(255),
    start_time DATE,
    sport_key varchar(255),
    sport_title varchar(255),
    1_SportsbookH2H_home_price varchar(255),
    1_H2H_home_price FLOAT(5,2) ,
    2_SportsbookH2H_home_price varchar(255),
    2_H2H_home_price FLOAT(5,2),
    3_SportsbookH2H_home_price varchar(255),
    3_H2H_home_price FLOAT(5,2),
    1_SportsbookH2H_away_price varchar(255),
    1_H2H_away_price FLOAT(5,2),
    2_SportsbookH2H_away_price varchar(255),
    2_H2H_away_price FLOAT(5,2),
    3_SportsbookH2H_away_price varchar(255),
    3_H2H_away_price FLOAT(5,2),
    1_Sportsbook_spread_home_price varchar(255),
    1_spread_home_price FLOAT(5,2),
    1_home_spread FLOAT(4,1),
    2_Sportsbook_spread_home_price varchar(255),
    2_spread_home_price FLOAT(5,2),
    2_home_spread FLOAT(4,1),
    3_Sportsbook_spread_home_price varchar(255),
    3_spread_home_price FLOAT(5,2),
    3_home_spread FLOAT(4,1),
    1_Sportsbook_spread_away_price varchar(255),
    1_spread_away_price FLOAT(5,2),
    1_away_spread FLOAT(4,1),
    2_Sportsbook_spread_away_price varchar(255),
    2_spread_away_price FLOAT(5,2),
    2_away_spread FLOAT(4,1),
    3_Sportsbook_spread_away_price varchar(255),
    3_spread_away_price FLOAT(5,2),
    3_away_spread FLOAT(4,1),
    1_Sportsbook_over_price varchar(255),
    1_over_price FLOAT(5,2),
    1_over FLOAT(4,1),
    2_Sportsbook_over_price varchar(255),
    2_over_price FLOAT(5,2),
    2_over FLOAT(4,1),
    3_Sportsbook_over_price varchar(255),
    3_over_price FLOAT(5,2),
    3_over FLOAT(4,1),
    1_Sportsbook_under_price varchar(255),
    1_under_price FLOAT(5,2),
    1_under FLOAT(4,1),
    2_Sportsbook_under_price varchar(255),
    2_under_price FLOAT(5,2),
    2_under FLOAT(4,1),
    3_Sportsbook_under_price varchar(255),
    3_under_price FLOAT(5,2),
    3_under FLOAT(4,1),
    1_H2H_home_price_ST varchar(255),
    2_H2H_home_price_ST varchar(255),
    3_H2H_home_price_ST varchar(255),
    1_H2H_away_price_ST varchar(255),
    2_H2H_away_price_ST varchar(255),
    3_H2H_away_price_ST varchar(255),
    1_spread_home_price_ST varchar(255),
    2_spread_home_price_ST varchar(255),
    3_spread_home_price_ST varchar(255),
    1_spread_away_price_ST varchar(255),
    2_spread_away_price_ST varchar(255),
    3_spread_away_price_ST varchar(255),
    1_over_price_ST varchar(255),
    2_over_price_ST varchar(255),
    3_over_price_ST varchar(255),
    1_under_price_ST varchar(255),
    2_under_price_ST varchar(255),
    3_under_price_ST varchar(255)
);