from django.db import connections
from django.db import models
from django.utils import timezone


class Games(models.Model):
    #id = models.CharField(max_length=100)
    game_id = models.CharField(primary_key=True, max_length=100 )
    away_team = models.CharField(max_length=100)
    home_team = models.CharField(max_length=100)
    #start_time = models.DateTimeField(default=timezone.now)
    start_time = models.CharField(max_length=100)
    sport_key = models.CharField(max_length=100)
    sport_title = models.CharField(max_length=100)
    class Meta:
	    db_table="games"


class Odds(models.Model):
    game_id = models.CharField(primary_key = True, max_length=100) #remove on launch
    #game_id = models.ForeignKey(Games, blank = True, null = False, related_name='topic_content_type', on_delete=models.CASCADE)
    #game_id = models.ManyToOneField(Games, blank = True, null = False, related_name='topic_content_type', on_delete=models.CASCADE)
    #game_id = models.CharField(max_length=100)
    # good column game_id = models.ManyToManyField(Games, max_length=100 )
    away_team = models.CharField(max_length=100)
    home_team = models.CharField(max_length=100)
    start_time = models.CharField(max_length=100)
    sport_key = models.CharField(max_length=100)
    sport_title = models.CharField(max_length=100)
    sportsbook = models.CharField(max_length=200)
    last_update = models.CharField(max_length=200)
    H2H_home_price = models.CharField(max_length=100)
    H2H_away_price = models.CharField(max_length=100)
    home_spread = models.CharField(max_length=100)
    away_spread = models.CharField(max_length=100)
    spread_home_price = models.CharField(max_length=100)
    spread_away_price = models.CharField(max_length=100)
    over = models.CharField(max_length=100)
    under = models.CharField(max_length=100)
    over_price = models.CharField(max_length=100)
    under_price = models.CharField(max_length=100)
#    class Meta:
#        db_table="odds"

class MLB(models.Model):
    game_id  = models.CharField(primary_key=True, max_length=100)
    away_team = models.CharField(max_length=100)
    home_team = models.CharField(max_length=100)
    start_time = models.CharField(max_length=100)
    sport_key = models.CharField(max_length=100)
    sport_title = models.CharField(max_length=100)
    SportsbookH2H_home_price1 = models.CharField(max_length=100)
    H2H_home_price1 = models.CharField(max_length=100)
    SportsbookH2H_home_price2 = models.CharField(max_length=100)
    H2H_home_price2 = models.CharField(max_length=100)
    SportsbookH2H_home_price3 = models.CharField(max_length=100)
    H2H_home_price3 = models.CharField(max_length=100)
    SportsbookH2H_away_price1 = models.CharField(max_length=100)
    H2H_away_price1 = models.CharField(max_length=100)
    SportsbookH2H_away_price2 = models.CharField(max_length=100)
    H2H_away_price2 = models.CharField(max_length=100)
    SportsbookH2H_away_price3 = models.CharField(max_length=100)
    H2H_away_price3 = models.CharField(max_length=100)
    Sportsbook_spread_home_price1 = models.CharField(max_length=100)
    spread_home_price1 = models.CharField(max_length=100)
    home_spread1 = models.CharField(max_length=100)
    Sportsbook_spread_home_price2 = models.CharField(max_length=100)
    spread_home_price2 = models.CharField(max_length=100)
    home_spread2 = models.CharField(max_length=100)
    Sportsbook_spread_home_price3 = models.CharField(max_length=100)
    spread_home_price3 = models.CharField(max_length=100)
    home_spread3 = models.CharField(max_length=100)
    Sportsbook_spread_away_price1 = models.CharField(max_length=100)
    spread_away_price1 = models.CharField(max_length=100)
    away_spread1 = models.CharField(max_length=100)
    Sportsbook_spread_away_price2 = models.CharField(max_length=100)
    spread_away_price2 = models.CharField(max_length=100)
    away_spread2 = models.CharField(max_length=100)
    Sportsbook_spread_away_price3 = models.CharField(max_length=100)
    spread_away_price3 = models.CharField(max_length=100)
    away_spread3 = models.CharField(max_length=100)
    Sportsbook_over_price1 = models.CharField(max_length=100)
    over_price1 = models.CharField(max_length=100)
    over1 = models.CharField(max_length=100)
    Sportsbook_over_price2 = models.CharField(max_length=100)
    over_price2 = models.CharField(max_length=100)
    over2 = models.CharField(max_length=100)
    Sportsbook_over_price3 = models.CharField(max_length=100)
    over_price3 = models.CharField(max_length=100)
    over3 = models.CharField(max_length=100)
    Sportsbook_under_price1 = models.CharField(max_length=100)
    under_price1 = models.CharField(max_length=100)
    under1 = models.CharField(max_length=100)
    Sportsbook_under_price2 = models.CharField(max_length=100)
    under_price2 = models.CharField(max_length=100)
    under2 = models.CharField(max_length=100)
    Sportsbook_under_price3 = models.CharField(max_length=100)
    under_price3 = models.CharField(max_length=100)
    under3 = models.CharField(max_length=100)
    H2H_home_price1_ST = models.CharField(max_length=100)
    H2H_home_price2_ST = models.CharField(max_length=100)
    H2H_home_price3_ST = models.CharField(max_length=100)
    H2H_away_price1_ST = models.CharField(max_length=100)
    H2H_away_price2_ST = models.CharField(max_length=100)
    H2H_away_price3_ST = models.CharField(max_length=100)
    spread_home_price1_ST = models.CharField(max_length=100)
    spread_home_price2_ST = models.CharField(max_length=100)
    spread_home_price3_ST = models.CharField(max_length=100)
    spread_away_price1_ST = models.CharField(max_length=100)
    spread_away_price2_ST = models.CharField(max_length=100)
    spread_away_price3_ST = models.CharField(max_length=100)
    over_price1_ST = models.CharField(max_length=100)
    over_price2_ST = models.CharField(max_length=100)
    over_price3_ST = models.CharField(max_length=100)
    under_price1_ST = models.CharField(max_length=100)
    under_price2_ST = models.CharField(max_length=100)
    under_price3_ST = models.CharField(max_length=100)
    class Meta:
	    db_table="sports_mlb"

class NBA(models.Model):
    game_id  = models.CharField(primary_key=True, max_length=100)
    away_team = models.CharField(max_length=100)
    home_team = models.CharField(max_length=100)
    start_time = models.CharField(max_length=100)
    sport_key = models.CharField(max_length=100)
    sport_title = models.CharField(max_length=100)
    SportsbookH2H_home_price1 = models.CharField(max_length=100)
    H2H_home_price1 = models.CharField(max_length=100)
    SportsbookH2H_home_price2 = models.CharField(max_length=100)
    H2H_home_price2 = models.CharField(max_length=100)
    SportsbookH2H_home_price3 = models.CharField(max_length=100)
    H2H_home_price3 = models.CharField(max_length=100)
    SportsbookH2H_away_price1 = models.CharField(max_length=100)
    H2H_away_price1 = models.CharField(max_length=100)
    SportsbookH2H_away_price2 = models.CharField(max_length=100)
    H2H_away_price2 = models.CharField(max_length=100)
    SportsbookH2H_away_price3 = models.CharField(max_length=100)
    H2H_away_price3 = models.CharField(max_length=100)
    Sportsbook_spread_home_price1 = models.CharField(max_length=100)
    spread_home_price1 = models.CharField(max_length=100)
    home_spread1 = models.CharField(max_length=100)
    Sportsbook_spread_home_price2 = models.CharField(max_length=100)
    spread_home_price2 = models.CharField(max_length=100)
    home_spread2 = models.CharField(max_length=100)
    Sportsbook_spread_home_price3 = models.CharField(max_length=100)
    spread_home_price3 = models.CharField(max_length=100)
    home_spread3 = models.CharField(max_length=100)
    Sportsbook_spread_away_price1 = models.CharField(max_length=100)
    spread_away_price1 = models.CharField(max_length=100)
    away_spread1 = models.CharField(max_length=100)
    Sportsbook_spread_away_price2 = models.CharField(max_length=100)
    spread_away_price2 = models.CharField(max_length=100)
    away_spread2 = models.CharField(max_length=100)
    Sportsbook_spread_away_price3 = models.CharField(max_length=100)
    spread_away_price3 = models.CharField(max_length=100)
    away_spread3 = models.CharField(max_length=100)
    Sportsbook_over_price1 = models.CharField(max_length=100)
    over_price1 = models.CharField(max_length=100)
    over1 = models.CharField(max_length=100)
    Sportsbook_over_price2 = models.CharField(max_length=100)
    over_price2 = models.CharField(max_length=100)
    over2 = models.CharField(max_length=100)
    Sportsbook_over_price3 = models.CharField(max_length=100)
    over_price3 = models.CharField(max_length=100)
    over3 = models.CharField(max_length=100)
    Sportsbook_under_price1 = models.CharField(max_length=100)
    under_price1 = models.CharField(max_length=100)
    under1 = models.CharField(max_length=100)
    Sportsbook_under_price2 = models.CharField(max_length=100)
    under_price2 = models.CharField(max_length=100)
    under2 = models.CharField(max_length=100)
    Sportsbook_under_price3 = models.CharField(max_length=100)
    under_price3 = models.CharField(max_length=100)
    under3 = models.CharField(max_length=100)
    H2H_home_price1_ST = models.CharField(max_length=100)
    H2H_home_price2_ST = models.CharField(max_length=100)
    H2H_home_price3_ST = models.CharField(max_length=100)
    H2H_away_price1_ST = models.CharField(max_length=100)
    H2H_away_price2_ST = models.CharField(max_length=100)
    H2H_away_price3_ST = models.CharField(max_length=100)
    spread_home_price1_ST = models.CharField(max_length=100)
    spread_home_price2_ST = models.CharField(max_length=100)
    spread_home_price3_ST = models.CharField(max_length=100)
    spread_away_price1_ST = models.CharField(max_length=100)
    spread_away_price2_ST = models.CharField(max_length=100)
    spread_away_price3_ST = models.CharField(max_length=100)
    over_price1_ST = models.CharField(max_length=100)
    over_price2_ST = models.CharField(max_length=100)
    over_price3_ST = models.CharField(max_length=100)
    under_price1_ST = models.CharField(max_length=100)
    under_price2_ST = models.CharField(max_length=100)
    under_price3_ST = models.CharField(max_length=100)
    class Meta:
	    db_table="sports_nba"

class NHL(models.Model):
    game_id  = models.CharField(primary_key=True, max_length=100)
    away_team = models.CharField(max_length=100)
    home_team = models.CharField(max_length=100)
    start_time = models.CharField(max_length=100)
    sport_key = models.CharField(max_length=100)
    sport_title = models.CharField(max_length=100)
    SportsbookH2H_home_price1 = models.CharField(max_length=100)
    H2H_home_price1 = models.CharField(max_length=100)
    SportsbookH2H_home_price2 = models.CharField(max_length=100)
    H2H_home_price2 = models.CharField(max_length=100)
    SportsbookH2H_home_price3 = models.CharField(max_length=100)
    H2H_home_price3 = models.CharField(max_length=100)
    SportsbookH2H_away_price1 = models.CharField(max_length=100)
    H2H_away_price1 = models.CharField(max_length=100)
    SportsbookH2H_away_price2 = models.CharField(max_length=100)
    H2H_away_price2 = models.CharField(max_length=100)
    SportsbookH2H_away_price3 = models.CharField(max_length=100)
    H2H_away_price3 = models.CharField(max_length=100)
    Sportsbook_spread_home_price1 = models.CharField(max_length=100)
    spread_home_price1 = models.CharField(max_length=100)
    home_spread1 = models.CharField(max_length=100)
    Sportsbook_spread_home_price2 = models.CharField(max_length=100)
    spread_home_price2 = models.CharField(max_length=100)
    home_spread2 = models.CharField(max_length=100)
    Sportsbook_spread_home_price3 = models.CharField(max_length=100)
    spread_home_price3 = models.CharField(max_length=100)
    home_spread3 = models.CharField(max_length=100)
    Sportsbook_spread_away_price1 = models.CharField(max_length=100)
    spread_away_price1 = models.CharField(max_length=100)
    away_spread1 = models.CharField(max_length=100)
    Sportsbook_spread_away_price2 = models.CharField(max_length=100)
    spread_away_price2 = models.CharField(max_length=100)
    away_spread2 = models.CharField(max_length=100)
    Sportsbook_spread_away_price3 = models.CharField(max_length=100)
    spread_away_price3 = models.CharField(max_length=100)
    away_spread3 = models.CharField(max_length=100)
    Sportsbook_over_price1 = models.CharField(max_length=100)
    over_price1 = models.CharField(max_length=100)
    over1 = models.CharField(max_length=100)
    Sportsbook_over_price2 = models.CharField(max_length=100)
    over_price2 = models.CharField(max_length=100)
    over2 = models.CharField(max_length=100)
    Sportsbook_over_price3 = models.CharField(max_length=100)
    over_price3 = models.CharField(max_length=100)
    over3 = models.CharField(max_length=100)
    Sportsbook_under_price1 = models.CharField(max_length=100)
    under_price1 = models.CharField(max_length=100)
    under1 = models.CharField(max_length=100)
    Sportsbook_under_price2 = models.CharField(max_length=100)
    under_price2 = models.CharField(max_length=100)
    under2 = models.CharField(max_length=100)
    Sportsbook_under_price3 = models.CharField(max_length=100)
    under_price3 = models.CharField(max_length=100)
    under3 = models.CharField(max_length=100)
    H2H_home_price1_ST = models.CharField(max_length=100)
    H2H_home_price2_ST = models.CharField(max_length=100)
    H2H_home_price3_ST = models.CharField(max_length=100)
    H2H_away_price1_ST = models.CharField(max_length=100)
    H2H_away_price2_ST = models.CharField(max_length=100)
    H2H_away_price3_ST = models.CharField(max_length=100)
    spread_home_price1_ST = models.CharField(max_length=100)
    spread_home_price2_ST = models.CharField(max_length=100)
    spread_home_price3_ST = models.CharField(max_length=100)
    spread_away_price1_ST = models.CharField(max_length=100)
    spread_away_price2_ST = models.CharField(max_length=100)
    spread_away_price3_ST = models.CharField(max_length=100)
    over_price1_ST = models.CharField(max_length=100)
    over_price2_ST = models.CharField(max_length=100)
    over_price3_ST = models.CharField(max_length=100)
    under_price1_ST = models.CharField(max_length=100)
    under_price2_ST = models.CharField(max_length=100)
    under_price3_ST = models.CharField(max_length=100)
    class Meta:
	    db_table="sports_nhl"